### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by leorosa** [nicolasedh/hexBlocker#2]
When compiling hexBlocker in recent linux distributions, the compilation of VTK results in an error:
> error: ‘GLintptr’ has not been declared

The solution is provided in:
http://stackoverflow.com/questions/28761702/getting-error-glintptr-has-not-been-declared-when-building-vtk-on-linux

Could you change the install script, in order to prevent such error?

**Comment by nicolasedh** [comment]
Fixed by commit: f01f05128d868c8ea4631cd3e5ccb54949d8a97d
Thank you for reporting and providing the fix!

/N
